version: '3.8'
services:
  #MSSQL
  mssql:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: mssql2019
#    restart: unless-stopped
    tty: true
    ports:
      - 11435:1433
    environment:
      SA_PASSWORD: aA123456789
      ACCEPT_EULA: Y
    volumes:
      - ./data:/var/opt/mssql/data
      - ./log:/var/opt/mssql/log 
      - ./secrets:/var/opt/mssql/secrets